/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: FractalSpace (https://sketchfab.com/fractalspace)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/notepad-ece41dfea050460d962b09a2c2596147
Title: Notepad
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function NotepadModel(props) {
  const { nodes, materials } = useGLTF('models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0.022, 0.858, 4.959]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
          <mesh geometry={nodes.Paper_PaperSide_0.geometry} material={materials.PaperSide} />
          <mesh geometry={nodes.Paper_Paper_0.geometry} material={materials.Paper} />
        </group>
        <mesh geometry={nodes.Binding_Plastic_0.geometry} material={materials.Plastic} position={[-0.011, 0.553, -2.48]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cartonage_Cardboard_0.geometry} material={materials.Cardboard} position={[0.022, 0.398, 4.959]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('models/scene.gltf')
